name: Build EXE for Mromarex

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --noconsole --name Mromarex mromarex_cookie_tool.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Mromarex-EXE
          path: dist/Mromarex.exe
