name: Build EXE for Mromarex

on:
  push:
    paths:
      - 'mromarex_cookie_tool.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --noconsole mromarex_cookie_tool.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Mromarex_EXE
          path: dist/Mromarex.exe
